const fs = require('fs');
const path = require('path');

const phase1Foods = [
  // ==========================================
  // BATCH P: Instant Noodles & Packaged Ready-to-Eat
  // ==========================================
  {
    id: 'maggi-masala-single',
    name: 'Maggi 2-Minute Masala Noodles',
    nameAlt: ['magi', 'instant noodles'],
    hindiName: 'मैगी मसाला',
    searchTerms: ['maggi', 'magi', '2 minute noodles', 'masala maggi'],
    category: 'packaged-food',
    subcategory: 'instant-noodle',
    itemType: 'snack',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 70,
    per100g: {
      calories: 442,
      protein: 10.0,
      carbs: 60.0,
      fat: 17.1,
      fiber: 2.0,
      sodium: 1228,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 2.0,
      calcium: 20
    },
    servings: [
      { id: 'packet', label: '1 packet', grams: 70 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg'],
    tags: ['snack', 'high-sodium', 'high-carb'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 70,
    cookingOilNote: 'Contains pre-added fat in the seasoning and noodle block.',
    estimatedOilG: 0,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: 'Calculated using typical 70g packet cooked in water. High sodium content.'
  },
  {
    id: 'maggi-atta-masala',
    name: 'Maggi Atta (Whole Wheat) Noodles',
    nameAlt: ['atta magi'],
    hindiName: 'मैगी आटा नूडल्स',
    searchTerms: ['maggi atta', 'wheat maggi', 'atta noodles'],
    category: 'packaged-food',
    subcategory: 'instant-noodle',
    itemType: 'snack',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 75,
    per100g: {
      calories: 386,
      protein: 10.6,
      carbs: 53.3,
      fat: 14.6,
      fiber: 5.3,
      sodium: 900,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 2.5,
      calcium: 40
    },
    servings: [
      { id: 'packet', label: '1 packet', grams: 75 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg'],
    tags: ['snack', 'high-carb'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 65,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: 'Slightly higher fiber than regular Maggi.'
  },
  {
    id: 'yippee-noodles-masala',
    name: 'Sunfeast YiPPee! Noodles',
    nameAlt: ['ipee noodles', 'yipee'],
    hindiName: 'यिप्पी नूडल्स',
    searchTerms: ['yippee', 'yipee', 'sunfeast', 'instant noodles'],
    category: 'packaged-food',
    subcategory: 'instant-noodle',
    itemType: 'snack',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 70,
    per100g: {
      calories: 500,
      protein: 11.4,
      carbs: 68.5,
      fat: 20.0,
      fiber: 2.0,
      sodium: 1100,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 25
    },
    servings: [
      { id: 'packet', label: '1 packet', grams: 70 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg'],
    tags: ['snack', 'high-carb', 'high-sodium'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 70,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: 'Similar macro profile to Maggi but slightly drier block.'
  },
  {
    id: 'nissin-cup-noodles-masala',
    name: 'Nissin Cup Noodles (Masala)',
    nameAlt: ['cup maggi'],
    hindiName: 'कप नूडल्स',
    searchTerms: ['cup noodles', 'nissin', 'masala cup', 'instant cup'],
    category: 'packaged-food',
    subcategory: 'instant-noodle',
    itemType: 'snack',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 70,
    per100g: {
      calories: 414,
      protein: 8.5,
      carbs: 54.2,
      fat: 17.1,
      fiber: 2.0,
      sodium: 950,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.0,
      calcium: 15
    },
    servings: [
      { id: 'cup', label: '1 cup', grams: 70 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg'],
    tags: ['snack', 'high-carb'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 70,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: '70g dry weight; swells to about 250g with water.'
  },
  {
    id: 'top-ramen-curry-noodles',
    name: 'Top Ramen Curry Noodles',
    nameAlt: ['ramen india'],
    hindiName: 'टॉप रेमन करी',
    searchTerms: ['top ramen', 'curry noodles', 'ramen', 'instant curry'],
    category: 'packaged-food',
    subcategory: 'instant-noodle',
    itemType: 'snack',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 70,
    per100g: {
      calories: 442,
      protein: 10.0,
      carbs: 60.0,
      fat: 17.1,
      fiber: 2.0,
      sodium: 1200,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 2.0,
      calcium: 20
    },
    servings: [
      { id: 'packet', label: '1 packet', grams: 70 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg'],
    tags: ['snack', 'high-sodium'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 70,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: 'Flat noodles, high sodium curry base.'
  },
  {
    id: 'knorr-soupy-noodles',
    name: 'Knorr Soupy Noodles',
    nameAlt: ['soupy maggi'],
    hindiName: 'नोर सूपी नूडल्स',
    searchTerms: ['knorr', 'soupy noodles', 'knor', 'soup maggi'],
    category: 'packaged-food',
    subcategory: 'instant-noodle',
    itemType: 'snack',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 66,
    per100g: {
      calories: 363,
      protein: 7.5,
      carbs: 54.5,
      fat: 13.6,
      fiber: 2.0,
      sodium: 1050,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 15
    },
    servings: [
      { id: 'packet', label: '1 packet', grams: 66 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg'],
    tags: ['snack', 'high-sodium'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 68,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: 'More liquid per gram than standard noodles.'
  },
  {
    id: 'maggi-hot-heads-cup',
    name: 'Maggi Hot Heads Cup Noodles',
    nameAlt: ['spicy maggi cup'],
    hindiName: 'मैगी हॉट हेड्स',
    searchTerms: ['hot heads', 'maggi spicy cup', 'spicy maggi'],
    category: 'packaged-food',
    subcategory: 'instant-noodle',
    itemType: 'snack',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 71,
    per100g: {
      calories: 422,
      protein: 8.4,
      carbs: 56.3,
      fat: 18.3,
      fiber: 2.0,
      sodium: 1100,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 20
    },
    servings: [
      { id: 'cup', label: '1 cup', grams: 71 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg'],
    tags: ['snack', 'spicy'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 70,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: 'Extra chili oil packet.'
  },
  {
    id: 'mtr-ready-to-eat-rajma-rice',
    name: 'MTR Ready to Eat Rajma Rice',
    nameAlt: ['packaged rajma chawal'],
    hindiName: 'एमटीआर राजमा चावल',
    searchTerms: ['mtr rajma', 'rajma rice ready', 'packaged rajma'],
    category: 'packaged-food',
    subcategory: 'cloud-kitchen',
    itemType: 'dish',
    state: 'cooked',
    region: 'north',
    defaultServingGrams: 300,
    per100g: {
      calories: 160,
      protein: 5.0,
      carbs: 24.0,
      fat: 5.0,
      fiber: 4.5,
      sodium: 350,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.8,
      calcium: 30
    },
    servings: [
      { id: 'packet', label: '1 packet', grams: 300 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg'],
    tags: ['lunch', 'dinner'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: true,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 58,
    cookingOilNote: null,
    estimatedOilG: 3,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: 'Retort packaging format.'
  },
  {
    id: 'mtr-ready-to-eat-dal-fry',
    name: 'MTR Ready to Eat Dal Fry',
    nameAlt: ['packaged dal'],
    hindiName: 'एमटीआर दाल फ्राई',
    searchTerms: ['mtr dal fry', 'packaged dal'],
    category: 'packaged-food',
    subcategory: 'indian-packaged-namkeen',
    itemType: 'dish',
    state: 'cooked',
    region: 'north',
    defaultServingGrams: 300,
    per100g: {
      calories: 100,
      protein: 5.0,
      carbs: 12.0,
      fat: 3.0,
      fiber: 3.0,
      sodium: 380,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 20
    },
    servings: [
      { id: 'packet', label: '1 packet', grams: 300 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg'],
    tags: ['lunch', 'dinner'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: true,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 48,
    cookingOilNote: null,
    estimatedOilG: 2,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: 'Needs rice or roti added separately.'
  },
  {
    id: 'canned-baked-beans-generic',
    name: 'Canned Baked Beans (Generic)',
    nameAlt: ['heinz baked beans', 'beans in tomato sauce'],
    hindiName: 'बेक्ड बीन्स',
    searchTerms: ['baked beans', 'canned beans', 'heinz beans', 'tomato beans'],
    category: 'packaged-food',
    subcategory: 'cafe-food',
    itemType: 'dish',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 200,
    per100g: {
      calories: 95,
      protein: 5.0,
      carbs: 17.0,
      fat: 0.5,
      fiber: 4.0,
      sodium: 300,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 30
    },
    servings: [
      { id: 'can-half', label: 'Half can', grams: 200 },
      { id: 'can-full', label: 'Full can', grams: 400 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['breakfast', 'high-fiber'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 48,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: 'Low fat, high sugar from tomato sauce. Often paired with toast.'
  },

  // ==========================================
  // BATCH Q: Dry Fruits, Nuts & Seeds
  // ==========================================
  {
    id: 'almonds-raw',
    name: 'Almonds (Raw/Soaked)',
    nameAlt: ['badam'],
    hindiName: 'बादाम',
    searchTerms: ['almonds', 'badam', 'nuts', 'soaked badam'],
    category: 'fruit', // used for nuts universally in this schema
    subcategory: 'dry-fruit',
    itemType: 'snack',
    state: 'raw',
    region: 'pan-indian',
    defaultServingGrams: 14, // 10 pcs
    per100g: {
      calories: 579,
      protein: 21.0,
      carbs: 22.0,
      fat: 50.0,
      fiber: 12.0,
      sodium: 1,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 3.7,
      calcium: 268
    },
    servings: [
      { id: 'handful', label: '1 handful (10 pcs)', grams: 14 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['snack', 'healthy-fats', 'high-protein'],
    isProcessed: false,
    isFastingFood: true,
    fastingTypes: ['navratri', 'ekadashi'],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 15,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'USDA',
    confidence: 'high',
    notes: 'Superfood. Rich in Vitamin E and Magnesium.'
  },
  {
    id: 'cashews-raw',
    name: 'Cashews (Raw)',
    nameAlt: ['kaju'],
    hindiName: 'काजू',
    searchTerms: ['cashew', 'kaju', 'nuts'],
    category: 'fruit',
    subcategory: 'dry-fruit',
    itemType: 'snack',
    state: 'raw',
    region: 'pan-indian',
    defaultServingGrams: 15, // 10 pcs
    per100g: {
      calories: 553,
      protein: 18.2,
      carbs: 30.2,
      fat: 43.8,
      fiber: 3.3,
      sodium: 12,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 6.7,
      calcium: 37
    },
    servings: [
      { id: 'handful', label: '1 handful (10 pcs)', grams: 15 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['snack', 'healthy-fats'],
    isProcessed: false,
    isFastingFood: true,
    fastingTypes: ['navratri', 'ekadashi'],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 25,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'USDA',
    confidence: 'high',
    notes: 'Higher carbs than almonds/walnuts.'
  },
  {
    id: 'walnuts-raw',
    name: 'Walnuts (Raw)',
    nameAlt: ['akhrot'],
    hindiName: 'अखरोट',
    searchTerms: ['walnuts', 'akhrot', 'brain food', 'nuts'],
    category: 'fruit',
    subcategory: 'dry-fruit',
    itemType: 'snack',
    state: 'raw',
    region: 'pan-indian',
    defaultServingGrams: 14,
    per100g: {
      calories: 654,
      protein: 15.2,
      carbs: 13.7,
      fat: 65.2,
      fiber: 6.7,
      sodium: 2,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 2.9,
      calcium: 98
    },
    servings: [
      { id: 'handful', label: '4 halves', grams: 14 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['snack', 'healthy-fats', 'high-fat'],
    isProcessed: false,
    isFastingFood: true,
    fastingTypes: ['navratri', 'ekadashi'],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 15,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'USDA',
    confidence: 'high',
    notes: 'Excellent source of Omega-3 ALA.'
  },
  {
    id: 'peanuts-roasted',
    name: 'Peanuts (Roasted)',
    nameAlt: ['moongphali', 'shengdana'],
    hindiName: 'मूंगफली',
    searchTerms: ['peanuts', 'moongphali', 'roasted peanuts', 'shengdana'],
    category: 'fruit',
    subcategory: 'dry-fruit',
    itemType: 'snack',
    state: 'roasted',
    region: 'pan-indian',
    defaultServingGrams: 30,
    per100g: {
      calories: 567,
      protein: 25.8,
      carbs: 16.1,
      fat: 49.2,
      fiber: 8.5,
      sodium: 18,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 4.6,
      calcium: 92
    },
    servings: [
      { id: 'handful', label: '1 handful', grams: 30 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['snack', 'high-protein', 'budget-friendly'],
    isProcessed: false,
    isFastingFood: true,
    fastingTypes: ['navratri', 'ekadashi'],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 14,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'USDA',
    confidence: 'high',
    notes: 'Inexpensive plant protein powerhouse.'
  },
  {
    id: 'dates-khajoor',
    name: 'Dates (Khajoor)',
    nameAlt: ['pind khajoor', 'medjool dates'],
    hindiName: 'खजूर',
    searchTerms: ['dates', 'khajoor', 'khajur', 'sweet dates'],
    category: 'fruit',
    subcategory: 'dry-fruit',
    itemType: 'snack',
    state: 'raw',
    region: 'pan-indian',
    defaultServingGrams: 40,
    per100g: {
      calories: 277,
      protein: 1.8,
      carbs: 75.0,
      fat: 0.2,
      fiber: 8.0,
      sodium: 1,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 0.9,
      calcium: 64
    },
    servings: [
      { id: 'piece', label: '2 pieces', grams: 40 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['snack', 'high-sugar', 'natural-sweetener'],
    isProcessed: false,
    isFastingFood: true,
    fastingTypes: ['navratri', 'ekadashi'],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 42,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'USDA',
    confidence: 'high',
    notes: 'Great quick-energy pre-workout snack.'
  },
  {
    id: 'peanut-butter-creamy',
    name: 'Peanut Butter (Creamy)',
    nameAlt: ['smooth peanut butter'],
    hindiName: 'पीनट बटर',
    searchTerms: ['peanut butter', 'pb', 'creamy peanut butter', 'sandwich butter'],
    category: 'condiment',
    subcategory: 'spreads',
    itemType: 'condiment',
    state: 'raw',
    region: 'pan-indian',
    defaultServingGrams: 15,
    per100g: {
      calories: 588,
      protein: 25.0,
      carbs: 20.0,
      fat: 50.0,
      fiber: 6.0,
      sodium: 400,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.9,
      calcium: 43
    },
    servings: [
      { id: 'tbsp', label: '1 tbsp', grams: 15 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain'],
    tags: ['snack', 'high-protein', 'high-fat'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 14,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'USDA',
    confidence: 'high',
    notes: 'Generic commercial value with some added sugar/salt.'
  },
  {
    id: 'flax-seeds',
    name: 'Flax Seeds',
    nameAlt: ['alsi'],
    hindiName: 'अलसी',
    searchTerms: ['flax seeds', 'alsi', 'flaxseed'],
    category: 'condiment',
    subcategory: 'seeds',
    itemType: 'condiment',
    state: 'raw',
    region: 'pan-indian',
    defaultServingGrams: 10,
    per100g: {
      calories: 534,
      protein: 18.3,
      carbs: 28.9,
      fat: 42.2,
      fiber: 27.3,
      sodium: 30,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 5.7,
      calcium: 255
    },
    servings: [
      { id: 'tbsp', label: '1 tbsp', grams: 10 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain'],
    tags: ['healthy-fats', 'high-fiber'],
    isProcessed: false,
    isFastingFood: true,
    fastingTypes: ['navratri', 'ekadashi'],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 32,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'USDA',
    confidence: 'high',
    notes: 'Excellent source of Omega 3.'
  },

  // ==========================================
  // BATCH R: Protein Bars & Health Snacks
  // ==========================================
  {
    id: 'ritebite-max-protein-choco-fudge',
    name: 'RiteBite Max Protein Bar (Choco Fudge)',
    nameAlt: ['rite bite bar'],
    hindiName: 'मैक्स प्रोटीन बार',
    searchTerms: ['ritebite', 'max protein', 'protein bar', 'choco fudge bar'],
    category: 'supplement',
    subcategory: 'protein-bar',
    itemType: 'snack',
    state: 'raw',
    region: 'pan-indian',
    defaultServingGrams: 67,
    per100g: {
      calories: 283,
      protein: 29.8,
      carbs: 25.3,
      fat: 8.9,
      fiber: 8.0,
      sodium: 250,
      vitaminB12: 2.0,
      vitaminD: 2.5,
      iron: 3.5,
      calcium: 150
    },
    servings: [
      { id: 'bar', label: '1 bar', grams: 67 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg'],
    tags: ['snack', 'high-protein'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: null,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: 'About 190 calories & 20g protein per 67g bar.'
  },
  {
    id: 'yogabar-protein-bar-almond-fudge',
    name: 'Yoga Bar Protein Bar (Almond Fudge)',
    nameAlt: ['yoga bar'],
    hindiName: 'योगा बार प्रोटीन बार',
    searchTerms: ['yoga bar', 'yogabar', 'protein bar almond'],
    category: 'supplement',
    subcategory: 'protein-bar',
    itemType: 'snack',
    state: 'raw',
    region: 'pan-indian',
    defaultServingGrams: 60,
    per100g: {
      calories: 333,
      protein: 25.0,
      carbs: 36.6,
      fat: 11.6,
      fiber: 8.0,
      sodium: 150,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 2.0,
      calcium: 120
    },
    servings: [
      { id: 'bar', label: '1 bar', grams: 60 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg', 'jain'],
    tags: ['snack', 'high-protein'],
    isProcessed: true,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: null,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'FSSAI-label',
    confidence: 'high',
    notes: 'Clean ingredients; ~200 calories per bar.'
  },

  // ==========================================
  // BATCH N/B6: Missing Drinks and Sides
  // ==========================================
  {
    id: 'sattu-drink-namkeen',
    name: 'Sattu Drink (Savoury/Namkeen)',
    nameAlt: ['sattu sharbat'],
    hindiName: 'सत्तू नमकीन',
    searchTerms: ['sattu', 'sattu sharbat', 'roasted gram drink', 'namkeen sattu'],
    category: 'drink',
    subcategory: 'cooling-drink',
    itemType: 'drink',
    state: 'raw',
    region: 'east',
    defaultServingGrams: 250, // 250ml
    per100g: {
      // For 100ml of drink (standard 250ml uses ~40g sattu powder)
      calories: 64, // 160 per glass
      protein: 3.2,
      carbs: 10.4,
      fat: 1.0,
      fiber: 2.5,
      sodium: 150,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 15
    },
    servings: [
      { id: 'glass', label: '1 glass', grams: 250 },
      { id: 'ml100', label: '100ml', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['high-protein', 'cooling', 'budget-friendly'],
    isProcessed: false,
    isFastingFood: false, // Bengal gram is a pulse, disallowed in standard Navratri
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: true,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 40,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'curated-estimate',
    confidence: 'high',
    notes: 'The native Indian protein shake. Rich in fiber and low GI.'
  },
  {
    id: 'chaas-plain',
    name: 'Chaas / Buttermilk (Plain, Mattha)',
    nameAlt: ['mattha', 'taak', 'majjiga'],
    hindiName: 'छाछ',
    searchTerms: ['chaas', 'buttermilk', 'mattha', 'taak', 'majjiga', 'chhas'],
    category: 'drink',
    subcategory: 'cooling-drink',
    itemType: 'drink',
    state: 'raw',
    region: 'pan-indian',
    defaultServingGrams: 200, // 200ml glass
    per100g: {
      calories: 20,
      protein: 1.2,
      carbs: 2.4,
      fat: 0.5,
      fiber: 0,
      sodium: 40,
      vitaminB12: 0.1,
      vitaminD: 0,
      iron: 0.1,
      calcium: 45
    },
    servings: [
      { id: 'glass', label: '1 glass', grams: 200 },
      { id: 'ml100', label: '100ml', grams: 100 }
    ],
    dietTypes: ['veg', 'jain'],
    tags: ['cooling', 'probiotic', 'low-calorie'],
    isProcessed: false,
    isFastingFood: true,
    fastingTypes: ['navratri', 'ekadashi'],
    isGlutenFree: true,
    isRecipe: true,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 30,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'healthifyme',
    confidence: 'high',
    notes: 'Highly hydrating probiotic. ~40 calories per 200ml glass.'
  },
  {
    id: 'paneer-bhurji',
    name: 'Paneer Bhurji (Scrambled Paneer)',
    nameAlt: ['masala paneer scramble'],
    hindiName: 'पनीर भुर्जी',
    searchTerms: ['paneer bhurji', 'scrambled paneer', 'paneer masala'],
    category: 'sabzi-veg',
    subcategory: 'north-indian',
    itemType: 'dish',
    state: 'cooked',
    region: 'north',
    defaultServingGrams: 150,
    per100g: {
      calories: 240,
      protein: 12.0,
      carbs: 6.0,
      fat: 18.0,
      fiber: 1.5,
      sodium: 300,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.0,
      calcium: 200
    },
    servings: [
      { id: 'katori', label: '1 katori', grams: 150 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg'],
    tags: ['lunch', 'dinner', 'high-protein', 'low-carb'],
    isProcessed: false,
    isFastingFood: false, // Uses onions usually
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: true,
    containsRootVeg: true,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 20,
    cookingOilNote: 'Cooked with oil/ghee and onions/tomatoes.',
    estimatedOilG: 8,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Excellent low carb protein source.'
  },
  {
    id: 'egg-bhurji-masala',
    name: 'Egg Bhurji (Indian Scrambled Eggs)',
    nameAlt: ['anda bhurji'],
    hindiName: 'अंडा भुर्जी',
    searchTerms: ['egg bhurji', 'anda bhurji', 'scrambled eggs', 'spicy egg'],
    category: 'non-veg',
    subcategory: 'egg-dish',
    itemType: 'dish',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 120, // ~ 2 eggs + veg/oil
    per100g: {
      calories: 183,
      protein: 11.5,
      carbs: 3.5,
      fat: 13.5,
      fiber: 0.5,
      sodium: 350,
      vitaminB12: 1.1,
      vitaminD: 1.0,
      iron: 1.4,
      calcium: 45
    },
    servings: [
      { id: 'plate', label: '1 plate (2 eggs)', grams: 120 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['egg', 'nonveg'],
    tags: ['breakfast', 'high-protein', 'low-carb'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: true,
    containsRootVeg: true,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 0,
    cookingOilNote: 'Contains 1 tbsp oil/butter per 2 eggs.',
    estimatedOilG: 7,
    source: 'USDA',
    confidence: 'medium',
    notes: 'Standard recipe includes onions, tomatoes, green chilies.'
  }
];

const indianFoodsPath = path.join(__dirname, '../src/data/foods/indianFoods.js');

let fileContent = fs.readFileSync(indianFoodsPath, 'utf8');

const insertIndex = fileContent.lastIndexOf('];');

if (insertIndex === -1) {
    console.error("Could not find array end '];' in indianFoods.js");
    process.exit(1);
}

// Convert JSON formatted array to JS code
let injectedString = "";
for (let i = 0; i < phase1Foods.length; i++) {
   injectedString += "  ,\n  " + JSON.stringify(phase1Foods[i], null, 4).replace(/"([^"]+)":/g, '$1:');
}
injectedString += "\n";

// Inject
const newFileContent = fileContent.slice(0, insertIndex) + injectedString + fileContent.slice(insertIndex);

fs.writeFileSync(indianFoodsPath, newFileContent);
console.log(`Successfully appended ${phase1Foods.length} Phase 1 items to indianFoods.js`);
