const fs = require('fs');
const path = require('path');

const batch4Foods = [
  // ==========================================
  // BATCH 4: Breakfast & Tiffin
  // ==========================================
  {
    id: 'masala-dosa',
    name: 'Masala Dosa',
    nameAlt: ['dosai', 'potato stuffed dosa'],
    hindiName: 'मसाला डोसा',
    searchTerms: ['dosa', 'masala dosa', 'dosai', 'crepe'],
    category: 'breakfast',
    subcategory: 'south-indian',
    itemType: 'dish',
    state: 'cooked',
    region: 'south',
    defaultServingGrams: 150,
    per100g: {
      calories: 165,
      protein: 3.5,
      carbs: 23.0,
      fat: 6.0,
      fiber: 2.0,
      sodium: 250,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.0,
      calcium: 15
    },
    servings: [
      { id: 'piece', label: '1 medium dosa', grams: 150 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['breakfast', 'high-carb'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: true, // Aloo masala
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 65,
    cookingOilNote: 'Values include oil/ghee used for roasting.',
    estimatedOilG: 5,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Excludes chutney and sambar calories.'
  },
  {
    id: 'plain-dosa',
    name: 'Plain Dosa',
    nameAlt: ['sada dosa'],
    hindiName: 'सादा डोसा',
    searchTerms: ['dosa', 'plain dosa', 'sada dosa'],
    category: 'breakfast',
    subcategory: 'south-indian',
    itemType: 'dish',
    state: 'cooked',
    region: 'south',
    defaultServingGrams: 100,
    per100g: {
      calories: 133,
      protein: 3.0,
      carbs: 25.0,
      fat: 2.5,
      fiber: 1.0,
      sodium: 200,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 0.8,
      calcium: 10
    },
    servings: [
      { id: 'piece', label: '1 medium dosa', grams: 100 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['breakfast', 'high-carb', 'budget-friendly'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 75,
    cookingOilNote: 'Includes minimal oil for roasting.',
    estimatedOilG: 2,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'A healthier choice than masala dosa, but very high GI.'
  },
  {
    id: 'idli-steamed',
    name: 'Idli (Steamed Rice Cake)',
    nameAlt: ['rice idli'],
    hindiName: 'इडली',
    searchTerms: ['idli', 'steamed idli', 'rice cake'],
    category: 'breakfast',
    subcategory: 'south-indian',
    itemType: 'dish',
    state: 'steamed',
    region: 'south',
    defaultServingGrams: 40,
    per100g: {
      calories: 145,
      protein: 4.5,
      carbs: 32.0,
      fat: 0.2,
      fiber: 1.5,
      sodium: 150,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 0.5,
      calcium: 15
    },
    servings: [
      { id: 'piece', label: '1 medium idli', grams: 40 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['breakfast', 'snack', 'low-fat', 'budget-friendly'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 70,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'healthifyme',
    confidence: 'high',
    notes: 'Does not include sambar or chutney calories. Healthy low fat option.'
  },
  {
    id: 'medu-vada',
    name: 'Medu Vada (Fried Lentil Donut)',
    nameAlt: ['urad dal vada', 'vadai'],
    hindiName: 'मेदु वडा',
    searchTerms: ['vada', 'vadai', 'medu vada', 'fried donut'],
    category: 'breakfast',
    subcategory: 'south-indian',
    itemType: 'dish',
    state: 'fried',
    region: 'south',
    defaultServingGrams: 50,
    per100g: {
      calories: 335,
      protein: 10.0,
      carbs: 35.0,
      fat: 17.5,
      fiber: 5.0,
      sodium: 350,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 2.0,
      calcium: 40
    },
    servings: [
      { id: 'piece', label: '1 piece', grams: 50 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['breakfast', 'snack', 'high-fat'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 45,
    cookingOilNote: 'Deep fried. ~10-15g of oil absorbed per 100g.',
    estimatedOilG: 8,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'High calorie density due to deep frying.'
  },
  {
    id: 'upma-rava',
    name: 'Upma (Rava / Semolina)',
    nameAlt: ['suji upma', 'uppumavu'],
    hindiName: 'उपमा',
    searchTerms: ['upma', 'rava', 'suji', 'uppumavu'],
    category: 'breakfast',
    subcategory: 'south-indian',
    itemType: 'dish',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 150,
    per100g: {
      calories: 140,
      protein: 3.5,
      carbs: 22.0,
      fat: 4.5,
      fiber: 1.5,
      sodium: 250,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.2,
      calcium: 15
    },
    servings: [
      { id: 'katori', label: '1 katori', grams: 150 },
      { id: 'bowl', label: '1 bowl', grams: 200 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['breakfast', 'quick-to-make'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: true, // Often contains onion
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 68,
    cookingOilNote: 'Values assume standard oil tempering.',
    estimatedOilG: 5,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Add vegetables to increase fiber and reduce glycemic load.'
  },
  {
    id: 'poha',
    name: 'Poha (Flattened Rice)',
    nameAlt: ['kanda batata poha', 'aval', 'chiwda'],
    hindiName: 'पोहा',
    searchTerms: ['poha', 'chiwda', 'flattened rice', 'kanda batata'],
    category: 'breakfast',
    subcategory: 'west-indian',
    itemType: 'dish',
    state: 'cooked',
    region: 'west',
    defaultServingGrams: 150,
    per100g: {
      calories: 130,
      protein: 2.5,
      carbs: 23.0,
      fat: 3.5,
      fiber: 1.0,
      sodium: 220,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 12
    },
    servings: [
      { id: 'katori', label: '1 katori', grams: 150 },
      { id: 'bowl', label: '1 bowl', grams: 200 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['breakfast', 'snack', 'quick-to-make'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: true, // Batata (potato) & Kanda (onion)
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 65,
    cookingOilNote: 'Includes oil for tempering and peanuts.',
    estimatedOilG: 4,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Often garnished with peanuts and sev, which adds extra calories and fats.'
  },
  {
    id: 'chole-bhature',
    name: 'Chole Bhature',
    nameAlt: ['chana bhatura'],
    hindiName: 'छोले भटूरे',
    searchTerms: ['chole', 'bhature', 'chana', 'bhatura'],
    category: 'breakfast',
    subcategory: 'north-indian',
    itemType: 'dish',
    state: 'cooked',
    region: 'north',
    defaultServingGrams: 350,
    per100g: {
      calories: 220,
      protein: 6.0,
      carbs: 26.0,
      fat: 10.0,
      fiber: 4.0,
      sodium: 350,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 2.5,
      calcium: 40
    },
    servings: [
      { id: 'plate', label: '1 plate (2 bhature + chole)', grams: 350 },
      { id: 'restaurant-portion', label: '1 restaurant portion', grams: 500 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['breakfast', 'lunch', 'high-calorie', 'high-fat'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: true, // Onion-tomato gravy base for chole
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 60,
    cookingOilNote: 'Bhature are deep-fried; chole is oil-rich.',
    estimatedOilG: 20, // High per plate
    source: 'healthifyme',
    confidence: 'low',
    notes: 'Extremely high calorie. Portion size heavily dictates total calories.'
  },
  {
    id: 'besan-chilla',
    name: 'Besan Chilla (Gram Flour Pancake)',
    nameAlt: ['veg omelette', 'cheela'],
    hindiName: 'बेसन का चीला',
    searchTerms: ['besan', 'chilla', 'cheela', 'pancake', 'veg omelette'],
    category: 'breakfast',
    subcategory: 'north-indian',
    itemType: 'dish',
    state: 'cooked',
    region: 'north',
    defaultServingGrams: 80,
    per100g: {
      calories: 160,
      protein: 7.5,
      carbs: 22.0,
      fat: 4.5,
      fiber: 3.5,
      sodium: 250,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 2.0,
      calcium: 20
    },
    servings: [
      { id: 'piece', label: '1 chilla', grams: 80 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['breakfast', 'high-protein', 'quick-to-make'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: true, // Often contains onion
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 48,
    cookingOilNote: 'Assumes minimal oil brushed on pan.',
    estimatedOilG: 3,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'A great vegan high-protein alternative to eggs.'
  },
  {
    id: 'moong-dal-chilla',
    name: 'Moong Dal Chilla',
    nameAlt: ['pesarattu', 'moong cheela'],
    hindiName: 'मूंग दाल चीला',
    searchTerms: ['moong', 'chilla', 'cheela', 'pesarattu', 'pancake'],
    category: 'breakfast',
    subcategory: 'north-indian',
    itemType: 'dish',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 80,
    per100g: {
      calories: 155,
      protein: 8.5,
      carbs: 19.0,
      fat: 5.0,
      fiber: 3.0,
      sodium: 200,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 2.2,
      calcium: 25
    },
    servings: [
      { id: 'piece', label: '1 chilla', grams: 80 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'], // Can be jain if no onion
    tags: ['breakfast', 'high-protein', 'low-carb'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 45,
    cookingOilNote: '1 tsp oil assumed per chilla.',
    estimatedOilG: 4,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Often stuffed with paneer for extra protein.'
  },
  {
    id: 'uttapam',
    name: 'Uttapam (Mixed Veg)',
    nameAlt: ['south indian pizza'],
    hindiName: 'उत्तपम',
    searchTerms: ['uttapam', 'uthappam', 'oothappam'],
    category: 'breakfast',
    subcategory: 'south-indian',
    itemType: 'dish',
    state: 'cooked',
    region: 'south',
    defaultServingGrams: 120,
    per100g: {
      calories: 140,
      protein: 3.5,
      carbs: 23.0,
      fat: 3.5,
      fiber: 2.0,
      sodium: 280,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.0,
      calcium: 20
    },
    servings: [
      { id: 'piece', label: '1 medium uttapam', grams: 120 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['breakfast', 'high-carb'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: true, // Typical mix has onion
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 60,
    cookingOilNote: 'Pan-fried with some oil.',
    estimatedOilG: 3,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Veggies add fiber, lowering GI compared to plain dosa.'
  },
  {
    id: 'pongal',
    name: 'Ven Pongal (Ghee Rice & Lentils)',
    nameAlt: ['khara pongal'],
    hindiName: 'पोंगल',
    searchTerms: ['pongal', 'ven pongal', 'khara pongal', 'rice lentil'],
    category: 'breakfast',
    subcategory: 'south-indian',
    itemType: 'dish',
    state: 'cooked',
    region: 'south',
    defaultServingGrams: 200,
    per100g: {
      calories: 145,
      protein: 4.0,
      carbs: 19.0,
      fat: 6.0,
      fiber: 1.5,
      sodium: 250,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.2,
      calcium: 25
    },
    servings: [
      { id: 'bowl', label: '1 bowl', grams: 200 },
      { id: 'katori', label: '1 katori', grams: 150 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg', 'jain', 'nonveg'],
    tags: ['breakfast', 'comfort-food', 'high-fat'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 65,
    cookingOilNote: 'Rich in ghee. High fat content.',
    estimatedOilG: 6,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Ghee provides fat while rice & lentils are carbs/protein.'
  },
  {
    id: 'rava-idli',
    name: 'Rava Idli (Semolina Idli)',
    nameAlt: ['suji idli'],
    hindiName: 'रवा इडली',
    searchTerms: ['rava idli', 'suji idli', 'semolina idli'],
    category: 'breakfast',
    subcategory: 'south-indian',
    itemType: 'dish',
    state: 'steamed',
    region: 'south',
    defaultServingGrams: 60,
    per100g: {
      calories: 145,
      protein: 3.5,
      carbs: 23.0,
      fat: 4.5,
      fiber: 1.0,
      sodium: 250,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.0,
      calcium: 15
    },
    servings: [
      { id: 'piece', label: '1 piece', grams: 60 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg', 'nonveg'], // Often contains yogurt/dahi
    tags: ['breakfast', 'quick-to-make'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false, // Rava is wheat
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 60,
    cookingOilNote: 'Tempering before steaming adds small oil.',
    estimatedOilG: 2,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Slightly higher fat than rice idli due to cashew & mustard tempering.'
  },
  // ==========================================
  // BATCH 4: Snacks & Street Food
  // ==========================================
  {
    id: 'samosa',
    name: 'Samosa (Aloo / Potato)',
    nameAlt: ['aloo samosa', 'singara'],
    hindiName: 'समोसा',
    searchTerms: ['samosa', 'singara', 'aloo samosa', 'fried pastry'],
    category: 'snack-street',
    subcategory: 'fried-snack',
    itemType: 'dish',
    state: 'fried',
    region: 'pan-indian',
    defaultServingGrams: 80,
    per100g: {
      calories: 320,
      protein: 4.5,
      carbs: 35.0,
      fat: 18.0,
      fiber: 3.0,
      sodium: 400,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 20
    },
    servings: [
      { id: 'piece', label: '1 regular samosa', grams: 80 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['snack', 'high-calorie', 'high-fat', 'comfort-food'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: true, // Potato
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 70,
    cookingOilNote: 'Deep fried crust and oil in filling.',
    estimatedOilG: 12,
    source: 'healthifyme',
    confidence: 'high',
    notes: 'Classic street food. Roughly 250-260 calories per piece.'
  },
  {
    id: 'vada-pav',
    name: 'Vada Pav',
    nameAlt: ['bombay burger', 'batata vada pav'],
    hindiName: 'वड़ा पाव',
    searchTerms: ['vada pav', 'wada pav', 'bombay burger'],
    category: 'snack-street',
    subcategory: 'street-food',
    itemType: 'dish',
    state: 'cooked',
    region: 'west',
    defaultServingGrams: 120,
    per100g: {
      calories: 250,
      protein: 5.0,
      carbs: 33.0,
      fat: 10.5,
      fiber: 2.5,
      sodium: 450,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 2.0,
      calcium: 35
    },
    servings: [
      { id: 'piece', label: '1 piece', grams: 120 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['snack', 'high-calorie', 'high-carb', 'comfort-food'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: true, // Potato
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 75,
    cookingOilNote: 'Vada is deep fried. Pav is refined flour.',
    estimatedOilG: 8,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Total calories roughly 300 per vada pav.'
  },
  {
    id: 'pani-puri',
    name: 'Pani Puri / Golgappa',
    nameAlt: ['puchka', 'gupchup'],
    hindiName: 'पानी पूरी',
    searchTerms: ['pani puri', 'golgappa', 'puchka', 'gupchup', 'chaat'],
    category: 'snack-street',
    subcategory: 'chaat',
    itemType: 'dish',
    state: 'cooked',
    region: 'pan-indian',
    defaultServingGrams: 100, // Roughly 6 puris
    per100g: {
      calories: 140,
      protein: 3.0,
      carbs: 22.0,
      fat: 4.5,
      fiber: 2.0,
      sodium: 500,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 20
    },
    servings: [
      { id: 'plate', label: '1 plate (6 pieces)', grams: 100 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['snack', 'low-calorie'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false, // Puri can have suji/atta
    isRecipe: false,
    containsRootVeg: true, // Contains potato mixture
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 55,
    cookingOilNote: 'Puris are deep fried, but the water volume dilutes overall calorie density.',
    estimatedOilG: 3,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Surprising low calorie snack due to high water content, but high in sodium.'
  },
  {
    id: 'bhel-puri',
    name: 'Bhel Puri (With Chutney)',
    nameAlt: ['bheel'],
    hindiName: 'भेल पूरी',
    searchTerms: ['bhel', 'bhel puri', 'chaat'],
    category: 'snack-street',
    subcategory: 'chaat',
    itemType: 'dish',
    state: 'cooked',
    region: 'west',
    defaultServingGrams: 150,
    per100g: {
      calories: 160,
      protein: 4.0,
      carbs: 28.0,
      fat: 4.0,
      fiber: 3.5,
      sodium: 450,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 2.0,
      calcium: 30
    },
    servings: [
      { id: 'plate', label: '1 plate', grams: 150 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['snack', 'high-carb'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false, // contains sev/puri
    isRecipe: false,
    containsRootVeg: true, // Potato and Onion in mix
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 65,
    cookingOilNote: 'Sev and puri components are fried.',
    estimatedOilG: 3,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Sweet tamarind chutney adds sugar carbs.'
  },
  {
    id: 'pav-bhaji',
    name: 'Pav Bhaji (With Butter)',
    nameAlt: ['paav bhaji'],
    hindiName: 'पाव भाजी',
    searchTerms: ['pav', 'bhaji', 'pav bhaji', 'paavbhaji'],
    category: 'snack-street',
    subcategory: 'street-food',
    itemType: 'dish',
    state: 'cooked',
    region: 'west',
    defaultServingGrams: 300,
    per100g: {
      calories: 135,
      protein: 3.0,
      carbs: 18.0,
      fat: 5.5,
      fiber: 3.5,
      sodium: 380,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 30
    },
    servings: [
      { id: 'plate', label: '1 plate (2 pav + bhaji)', grams: 300 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['veg', 'nonveg'], // Butter/cheese makes it veg, not vegan
    tags: ['snack', 'lunch', 'high-calorie'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: true, // Lots of potato and onion
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 68,
    cookingOilNote: 'Heavily buttered. A lot of fat comes from Amul butter additions.',
    estimatedOilG: 12,
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'About 400 calories per plate. Adding extra butter increases calories steeply.'
  },
  {
    id: 'roasted-chana',
    name: 'Roasted Chana (Bengal Gram)',
    nameAlt: ['bhuna chana', 'dry roasted chickpea'],
    hindiName: 'भुना हुआ चना',
    searchTerms: ['chana', 'roasted chana', 'bhuna chana', 'gram'],
    category: 'snack-street',
    subcategory: 'dry-snack',
    itemType: 'base-food',
    state: 'roasted',
    region: 'pan-indian',
    defaultServingGrams: 30,
    per100g: {
      calories: 364,
      protein: 22.0,
      carbs: 50.0,
      fat: 5.2,
      fiber: 15.0,
      sodium: 80, // assuming slightly salted
      vitaminB12: 0,
      vitaminD: 0,
      iron: 5.5,
      calcium: 150
    },
    servings: [
      { id: 'handful', label: '1 handful', grams: 30 },
      { id: 'katori', label: '1 katori small', grams: 60 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['snack', 'high-protein', 'high-fiber', 'muscle-building', 'budget-friendly'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 28,
    cookingOilNote: null,
    estimatedOilG: 0,
    source: 'IFCT-2017',
    confidence: 'high',
    notes: 'Amazing protein-dense snack.'
  },
  {
    id: 'makhana-roasted',
    name: 'Makhana (Roasted Fox Nuts, Slightly Salted/Oiled)',
    nameAlt: ['lotus seeds', 'phool makhana'],
    hindiName: 'भुना हुआ मखाना',
    searchTerms: ['makhana', 'fox nuts', 'lotus seeds', 'roasted makhana'],
    category: 'snack-street',
    subcategory: 'dry-snack',
    itemType: 'base-food',
    state: 'roasted',
    region: 'pan-indian',
    defaultServingGrams: 30, // Makhana is extremely light
    per100g: {
      calories: 350,
      protein: 9.0,
      carbs: 77.0,
      fat: 0.5,
      fiber: 14.0,
      sodium: 150,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.4,
      calcium: 60
    },
    servings: [
      { id: 'bowl', label: '1 bowl', grams: 30 },
      { id: 'handful', label: '1 handful', grams: 15 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['snack', 'low-calorie', 'high-fiber'],
    isProcessed: false,
    isFastingFood: true,
    fastingTypes: ['navratri', 'ekadashi', 'jain-paryushana'],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 55,
    cookingOilNote: '100g usually includes ~2g ghee used for roasting.',
    estimatedOilG: 1, // for 30g
    source: 'IFCT-2017',
    confidence: 'medium',
    notes: 'Extremely light, so 30g is a very large portion visually.'
  },
  {
    id: 'khakhra-plain',
    name: 'Khakhra (Plain / Whole Wheat)',
    nameAlt: ['khakra'],
    hindiName: 'खाखरा',
    searchTerms: ['khakhra', 'khakra', 'gujarati snack', 'crispy roti'],
    category: 'snack-street',
    subcategory: 'dry-snack',
    itemType: 'base-food',
    state: 'roasted',
    region: 'west',
    defaultServingGrams: 20, // Weight of roughly 1 khakhra
    per100g: {
      calories: 420,
      protein: 10.5,
      carbs: 65.0,
      fat: 12.0,
      fiber: 6.0,
      sodium: 600,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 3.5,
      calcium: 40
    },
    servings: [
      { id: 'piece', label: '1 piece', grams: 20 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['snack', 'budget-friendly'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: false,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 55,
    cookingOilNote: 'Values include oil used in the dough.',
    estimatedOilG: 1, // small amount
    source: 'healthifyme',
    confidence: 'high',
    notes: 'Great substitute for fried chips. 1 piece is usually 80-90 calories.'
  },
  {
    id: 'dhokla',
    name: 'Khaman Dhokla (Besan Steamed, Sweet/Salty)',
    nameAlt: ['besan dhokla', 'khaman'],
    hindiName: 'ढोकला',
    searchTerms: ['dhokla', 'khaman', 'steamed besan', 'gujarati snack'],
    category: 'snack-street',
    subcategory: 'street-food',
    itemType: 'dish',
    state: 'steamed',
    region: 'west',
    defaultServingGrams: 50,
    per100g: {
      calories: 160,
      protein: 7.0,
      carbs: 22.0,
      fat: 4.5,
      fiber: 2.5,
      sodium: 400,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 30
    },
    servings: [
      { id: 'piece', label: '1 piece (medium)', grams: 50 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'jain', 'nonveg'],
    tags: ['snack', 'breakfast', 'low-fat'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true,
    isRecipe: false,
    containsRootVeg: false,
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 55,
    cookingOilNote: 'Oil primarily from mustard seed tempering on top.',
    estimatedOilG: 1, // per piece
    source: 'healthifyme',
    confidence: 'high',
    notes: 'Healthy snack option. Sugar water tempering adds to carbs.'
  },
  {
    id: 'pakora-onion',
    name: 'Onion Pakora (Pyaz Ke Pakode, Bhajiya)',
    nameAlt: ['onion bhaji', 'kanda bhaji'],
    hindiName: 'प्याज के पकोड़े',
    searchTerms: ['pakora', 'bhajiya', 'onion bhaji', 'pyaz pakoda', 'fritters'],
    category: 'snack-street',
    subcategory: 'fried-snack',
    itemType: 'dish',
    state: 'fried',
    region: 'pan-indian',
    defaultServingGrams: 50,
    per100g: {
      calories: 290,
      protein: 6.0,
      carbs: 25.0,
      fat: 18.0,
      fiber: 3.5,
      sodium: 350,
      vitaminB12: 0,
      vitaminD: 0,
      iron: 1.5,
      calcium: 35
    },
    servings: [
      { id: 'piece', label: '1 medium pakora', grams: 25 },
      { id: 'handful', label: '1 small plate', grams: 100 },
      { id: 'g100', label: '100g', grams: 100 }
    ],
    dietTypes: ['vegan', 'veg', 'nonveg'],
    tags: ['snack', 'high-fat'],
    isProcessed: false,
    isFastingFood: false,
    fastingTypes: [],
    isGlutenFree: true, // Besan is gluten-free
    isRecipe: false,
    containsRootVeg: true, // Onion is root veg
    hasBeverageModifiers: false,
    supportedConsistencyTypes: [],
    consistencyMultipliers: {},
    gi: 60,
    cookingOilNote: 'Deep fried item.',
    estimatedOilG: 15, // per 100g
    source: 'healthifyme',
    confidence: 'medium',
    notes: 'Extremely high calorie density due to deep frying.'
  }
];

const indianFoodsPath = path.join(__dirname, '../src/data/foods/indianFoods.js');

let fileContent = fs.readFileSync(indianFoodsPath, 'utf8');

// Find the last index of '];' in the file
const insertIndex = fileContent.lastIndexOf('];');

if (insertIndex === -1) {
    console.error("Could not find array end '];' in indianFoods.js");
    process.exit(1);
}

// Convert JSON formatted array to JS code
let injectedString = "";
for (let i = 0; i < batch4Foods.length; i++) {
   injectedString += "  ,\n  " + JSON.stringify(batch4Foods[i], null, 4).replace(/"([^"]+)":/g, '$1:');
}
injectedString += "\n";

// Inject
const newFileContent = fileContent.slice(0, insertIndex) + injectedString + fileContent.slice(insertIndex);

fs.writeFileSync(indianFoodsPath, newFileContent);
console.log("Successfully appended Batch 4 items to indianFoods.js");
